-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMtp8MoCmFfaZqm7J
b16IVIjroSrnfMzR74PLCa8IUVegCgYIKoZIzj0DAQehRANCAAR9eNB+mgSFufRu
A+27lB86TTExFht5CkSXyvZxfLAlYYQFvaqNy62AzEMB5UawRST5mBaLX0MKtesb
7ccb0cGT
-----END PRIVATE KEY-----